################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
board/CubeMX_Config/Core/Src \
board \
board/port \
libraries/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc \
libraries/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates \
libraries/STM32H7xx_HAL/STM32H7xx_HAL_Driver/Src \
libraries/drivers \
libraries/rt_ota_lib/src \
libraries/touchgfx_lib/TouchGFX/App \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/heartline_screen \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/main_screen \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__designer \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/gui/src/heartline_screen \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/gui/src/main_screen \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/simulator \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
libraries/touchgfx_lib/TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
libraries/touchgfx_lib/TouchGFX/generated/fonts/src \
libraries/touchgfx_lib/TouchGFX/generated/gui_generated/src/common \
libraries/touchgfx_lib/TouchGFX/generated/gui_generated/src/heartline_screen \
libraries/touchgfx_lib/TouchGFX/generated/gui_generated/src/main_screen \
libraries/touchgfx_lib/TouchGFX/generated/images/src \
libraries/touchgfx_lib/TouchGFX/generated/images/src/__designer \
libraries/touchgfx_lib/TouchGFX/generated/texts/src \
libraries/touchgfx_lib/TouchGFX/gui/src/common \
libraries/touchgfx_lib/TouchGFX/gui/src/heartline_screen \
libraries/touchgfx_lib/TouchGFX/gui/src/main_screen \
libraries/touchgfx_lib/TouchGFX/gui/src/model \
libraries/touchgfx_lib/TouchGFX/target \
libraries/touchgfx_lib/TouchGFX/target/generated \
model/net \
packages/EasyFlash-v4.1.0/src \
packages/fal-v0.5.0/samples/porting \
packages/fal-v0.5.0/src \
packages/gt9147-latest/src \
packages/rt_printf-latest \
packages/sys_load_monitor-v1.0.0 \
rt-thread/components/cplusplus \
rt-thread/components/dfs/filesystems/devfs \
rt-thread/components/dfs/filesystems/elmfat \
rt-thread/components/dfs/filesystems/elmfat/option \
rt-thread/components/dfs/src \
rt-thread/components/drivers/hwtimer \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/sdio \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi/sfud/src \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/src \
rt-thread/components/drivers/touch \
rt-thread/components/drivers/wlan \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/pthreads \
rt-thread/components/libc/termios \
rt-thread/components/libc/time \
rt-thread/components/net/lwip-2.0.2/src/api \
rt-thread/components/net/lwip-2.0.2/src/apps/ping \
rt-thread/components/net/lwip-2.0.2/src/arch \
rt-thread/components/net/lwip-2.0.2/src/core \
rt-thread/components/net/lwip-2.0.2/src/core/ipv4 \
rt-thread/components/net/lwip-2.0.2/src/netif \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal_socket/dfs_net \
rt-thread/components/net/sal_socket/impl \
rt-thread/components/net/sal_socket/socket \
rt-thread/components/net/sal_socket/src \
rt-thread/components/utilities/ymodem \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m7 \
rt-thread/src \

